// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: agent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Agent registration request
type RegisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"` // linux, windows, darwin
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	IpAddress     string                 `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	PublicKey     string                 `protobuf:"bytes,6,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterAgentRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *RegisterAgentRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterAgentRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RegisterAgentRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterAgentRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterAgentRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

// Agent registration response
type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterAgentResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterAgentResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterAgentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegisterAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Scan results request
type ScanResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ScanType      string                 `protobuf:"bytes,2,opt,name=scan_type,json=scanType,proto3" json:"scan_type,omitempty"` // full, quick, custom, real-time
	FilePaths     []string               `protobuf:"bytes,3,rep,name=file_paths,json=filePaths,proto3" json:"file_paths,omitempty"`
	Threats       []*Threat              `protobuf:"bytes,4,rep,name=threats,proto3" json:"threats,omitempty"`
	ScanTime      int64                  `protobuf:"varint,5,opt,name=scan_time,json=scanTime,proto3" json:"scan_time,omitempty"` // Unix timestamp
	Duration      int64                  `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`                 // in milliseconds
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`                      // completed, failed, in-progress
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResultsRequest) Reset() {
	*x = ScanResultsRequest{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResultsRequest) ProtoMessage() {}

func (x *ScanResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResultsRequest.ProtoReflect.Descriptor instead.
func (*ScanResultsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ScanResultsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ScanResultsRequest) GetScanType() string {
	if x != nil {
		return x.ScanType
	}
	return ""
}

func (x *ScanResultsRequest) GetFilePaths() []string {
	if x != nil {
		return x.FilePaths
	}
	return nil
}

func (x *ScanResultsRequest) GetThreats() []*Threat {
	if x != nil {
		return x.Threats
	}
	return nil
}

func (x *ScanResultsRequest) GetScanTime() int64 {
	if x != nil {
		return x.ScanTime
	}
	return 0
}

func (x *ScanResultsRequest) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *ScanResultsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Scan results response
type ScanResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResultsResponse) Reset() {
	*x = ScanResultsResponse{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResultsResponse) ProtoMessage() {}

func (x *ScanResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResultsResponse.ProtoReflect.Descriptor instead.
func (*ScanResultsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ScanResultsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScanResultsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Threat detected in scan
type Threat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	ThreatType    string                 `protobuf:"bytes,2,opt,name=threat_type,json=threatType,proto3" json:"threat_type,omitempty"`    // malware, heuristic, suspicious
	ThreatName    string                 `protobuf:"bytes,3,opt,name=threat_name,json=threatName,proto3" json:"threat_name,omitempty"`    // YARA rule name, hash match, etc.
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`                          // low, medium, high, critical
	ActionTaken   string                 `protobuf:"bytes,5,opt,name=action_taken,json=actionTaken,proto3" json:"action_taken,omitempty"` // quarantined, blocked, reported
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Threat) Reset() {
	*x = Threat{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Threat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Threat) ProtoMessage() {}

func (x *Threat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Threat.ProtoReflect.Descriptor instead.
func (*Threat) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Threat) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Threat) GetThreatType() string {
	if x != nil {
		return x.ThreatType
	}
	return ""
}

func (x *Threat) GetThreatName() string {
	if x != nil {
		return x.ThreatName
	}
	return ""
}

func (x *Threat) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Threat) GetActionTaken() string {
	if x != nil {
		return x.ActionTaken
	}
	return ""
}

// Get signatures request
type GetSignaturesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	LastSyncTime  string                 `protobuf:"bytes,2,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"` // ISO 8601 timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSignaturesRequest) Reset() {
	*x = GetSignaturesRequest{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignaturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignaturesRequest) ProtoMessage() {}

func (x *GetSignaturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignaturesRequest.ProtoReflect.Descriptor instead.
func (*GetSignaturesRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *GetSignaturesRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetSignaturesRequest) GetLastSyncTime() string {
	if x != nil {
		return x.LastSyncTime
	}
	return ""
}

// Get signatures response
type GetSignaturesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Signatures     []*Signature           `protobuf:"bytes,1,rep,name=signatures,proto3" json:"signatures,omitempty"`
	SignatureCount int32                  `protobuf:"varint,2,opt,name=signature_count,json=signatureCount,proto3" json:"signature_count,omitempty"`
	SyncTime       string                 `protobuf:"bytes,3,opt,name=sync_time,json=syncTime,proto3" json:"sync_time,omitempty"` // ISO 8601 timestamp
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSignaturesResponse) Reset() {
	*x = GetSignaturesResponse{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignaturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignaturesResponse) ProtoMessage() {}

func (x *GetSignaturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignaturesResponse.ProtoReflect.Descriptor instead.
func (*GetSignaturesResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *GetSignaturesResponse) GetSignatures() []*Signature {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *GetSignaturesResponse) GetSignatureCount() int32 {
	if x != nil {
		return x.SignatureCount
	}
	return 0
}

func (x *GetSignaturesResponse) GetSyncTime() string {
	if x != nil {
		return x.SyncTime
	}
	return ""
}

func (x *GetSignaturesResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Signature definition
type Signature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                               // yara, hash, heuristic
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                         // YARA rule content or hash
	HashType      string                 `protobuf:"bytes,5,opt,name=hash_type,json=hashType,proto3" json:"hash_type,omitempty"`       // md5, sha256 (for hash signatures)
	ThreatType    string                 `protobuf:"bytes,6,opt,name=threat_type,json=threatType,proto3" json:"threat_type,omitempty"` // malware family, trojan, etc.
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Version       string                 `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`                         // active, inactive, deprecated
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // ISO 8601 timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *Signature) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Signature) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Signature) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Signature) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Signature) GetHashType() string {
	if x != nil {
		return x.HashType
	}
	return ""
}

func (x *Signature) GetThreatType() string {
	if x != nil {
		return x.ThreatType
	}
	return ""
}

func (x *Signature) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Signature) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Signature) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Signature) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Event request
type EventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`       // process_creation, network_connection, file_access, etc.
	EventSource   string                 `protobuf:"bytes,3,opt,name=event_source,json=eventSource,proto3" json:"event_source,omitempty"` // agent, signature, heuristic
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Severity      string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`    // info, warning, high, critical
	Data          string                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`            // JSON string with event-specific details
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRequest) Reset() {
	*x = EventRequest{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequest) ProtoMessage() {}

func (x *EventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequest.ProtoReflect.Descriptor instead.
func (*EventRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *EventRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventRequest) GetEventSource() string {
	if x != nil {
		return x.EventSource
	}
	return ""
}

func (x *EventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *EventRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *EventRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Event response
type EventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *EventResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Heartbeat request
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Heartbeat response
type HeartbeatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ServerTime     int64                  `protobuf:"varint,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`             // Unix timestamp
	QuarantineMode bool                   `protobuf:"varint,4,opt,name=quarantine_mode,json=quarantineMode,proto3" json:"quarantine_mode,omitempty"` // If the agent should go into quarantine mode
	Commands       []*Command             `protobuf:"bytes,5,rep,name=commands,proto3" json:"commands,omitempty"`                                    // Pending commands for the agent
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *HeartbeatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HeartbeatResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *HeartbeatResponse) GetQuarantineMode() bool {
	if x != nil {
		return x.QuarantineMode
	}
	return false
}

func (x *HeartbeatResponse) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

// Command to be executed by the agent
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                             // scan, quarantine, update_policy, etc.
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`                         // target of the command
	Params        string                 `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`                         // JSON string with command parameters
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Command) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Command) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *Command) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\bsentinel\"\xc5\x01\n" +
	"\x14RegisterAgentRequest\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x05 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"public_key\x18\x06 \x01(\tR\tpublicKey\"z\n" +
	"\x15RegisterAgentResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xe8\x01\n" +
	"\x12ScanResultsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tscan_type\x18\x02 \x01(\tR\bscanType\x12\x1d\n" +
	"\n" +
	"file_paths\x18\x03 \x03(\tR\tfilePaths\x12*\n" +
	"\athreats\x18\x04 \x03(\v2\x10.sentinel.ThreatR\athreats\x12\x1b\n" +
	"\tscan_time\x18\x05 \x01(\x03R\bscanTime\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x03R\bduration\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"G\n" +
	"\x13ScanResultsResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa6\x01\n" +
	"\x06Threat\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1f\n" +
	"\vthreat_type\x18\x02 \x01(\tR\n" +
	"threatType\x12\x1f\n" +
	"\vthreat_name\x18\x03 \x01(\tR\n" +
	"threatName\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12!\n" +
	"\faction_taken\x18\x05 \x01(\tR\vactionTaken\"W\n" +
	"\x14GetSignaturesRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12$\n" +
	"\x0elast_sync_time\x18\x02 \x01(\tR\flastSyncTime\"\xaa\x01\n" +
	"\x15GetSignaturesResponse\x123\n" +
	"\n" +
	"signatures\x18\x01 \x03(\v2\x13.sentinel.SignatureR\n" +
	"signatures\x12'\n" +
	"\x0fsignature_count\x18\x02 \x01(\x05R\x0esignatureCount\x12\x1b\n" +
	"\tsync_time\x18\x03 \x01(\tR\bsyncTime\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\x8e\x02\n" +
	"\tSignature\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1b\n" +
	"\thash_type\x18\x05 \x01(\tR\bhashType\x12\x1f\n" +
	"\vthreat_type\x18\x06 \x01(\tR\n" +
	"threatType\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\xdb\x01\n" +
	"\fEventRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12!\n" +
	"\fevent_source\x18\x03 \x01(\tR\veventSource\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x12\x12\n" +
	"\x04data\x18\x06 \x01(\tR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\"A\n" +
	"\rEventResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"a\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\xbe\x01\n" +
	"\x11HeartbeatResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vserver_time\x18\x03 \x01(\x03R\n" +
	"serverTime\x12'\n" +
	"\x0fquarantine_mode\x18\x04 \x01(\bR\x0equarantineMode\x12-\n" +
	"\bcommands\x18\x05 \x03(\v2\x11.sentinel.CommandR\bcommands\"|\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x16\n" +
	"\x06params\x18\x04 \x01(\tR\x06params\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt2\x86\x03\n" +
	"\fAgentService\x12P\n" +
	"\rRegisterAgent\x12\x1e.sentinel.RegisterAgentRequest\x1a\x1f.sentinel.RegisterAgentResponse\x12N\n" +
	"\x0fSendScanResults\x12\x1c.sentinel.ScanResultsRequest\x1a\x1d.sentinel.ScanResultsResponse\x12P\n" +
	"\rGetSignatures\x12\x1e.sentinel.GetSignaturesRequest\x1a\x1f.sentinel.GetSignaturesResponse\x12<\n" +
	"\tSendEvent\x12\x16.sentinel.EventRequest\x1a\x17.sentinel.EventResponse\x12D\n" +
	"\tHeartbeat\x12\x1a.sentinel.HeartbeatRequest\x1a\x1b.sentinel.HeartbeatResponseB*Z(github.com/0xA1M/sentinel-server/grpc/pbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_agent_proto_goTypes = []any{
	(*RegisterAgentRequest)(nil),  // 0: sentinel.RegisterAgentRequest
	(*RegisterAgentResponse)(nil), // 1: sentinel.RegisterAgentResponse
	(*ScanResultsRequest)(nil),    // 2: sentinel.ScanResultsRequest
	(*ScanResultsResponse)(nil),   // 3: sentinel.ScanResultsResponse
	(*Threat)(nil),                // 4: sentinel.Threat
	(*GetSignaturesRequest)(nil),  // 5: sentinel.GetSignaturesRequest
	(*GetSignaturesResponse)(nil), // 6: sentinel.GetSignaturesResponse
	(*Signature)(nil),             // 7: sentinel.Signature
	(*EventRequest)(nil),          // 8: sentinel.EventRequest
	(*EventResponse)(nil),         // 9: sentinel.EventResponse
	(*HeartbeatRequest)(nil),      // 10: sentinel.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 11: sentinel.HeartbeatResponse
	(*Command)(nil),               // 12: sentinel.Command
}
var file_agent_proto_depIdxs = []int32{
	4,  // 0: sentinel.ScanResultsRequest.threats:type_name -> sentinel.Threat
	7,  // 1: sentinel.GetSignaturesResponse.signatures:type_name -> sentinel.Signature
	12, // 2: sentinel.HeartbeatResponse.commands:type_name -> sentinel.Command
	0,  // 3: sentinel.AgentService.RegisterAgent:input_type -> sentinel.RegisterAgentRequest
	2,  // 4: sentinel.AgentService.SendScanResults:input_type -> sentinel.ScanResultsRequest
	5,  // 5: sentinel.AgentService.GetSignatures:input_type -> sentinel.GetSignaturesRequest
	8,  // 6: sentinel.AgentService.SendEvent:input_type -> sentinel.EventRequest
	10, // 7: sentinel.AgentService.Heartbeat:input_type -> sentinel.HeartbeatRequest
	1,  // 8: sentinel.AgentService.RegisterAgent:output_type -> sentinel.RegisterAgentResponse
	3,  // 9: sentinel.AgentService.SendScanResults:output_type -> sentinel.ScanResultsResponse
	6,  // 10: sentinel.AgentService.GetSignatures:output_type -> sentinel.GetSignaturesResponse
	9,  // 11: sentinel.AgentService.SendEvent:output_type -> sentinel.EventResponse
	11, // 12: sentinel.AgentService.Heartbeat:output_type -> sentinel.HeartbeatResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
